pipeline {
    agent any
    stages {

        /* Begin Template
        stage('template'){
            steps{
                sh 'scripts'
            }
        }
        End template*/

        stage('Setting up database'){
            steps{
                sh 'bash ./Jenkins/Scripts/Database/database.sh'
            }
        }

        stage('Testing'){
            steps{
                sh 'bash ./Jenkins/Scripts/Test/test_app.sh'
            }
        }

        stage('Build images'){
        steps{
             withCredentials([string(credentialsId: 'DOCKER_USERNAME', variable: 'DOCKER_USERNAME'), string(credentialsId: 'DOCKER_PASSWORD', variable: 'DOCKER_PASSWORD')]) {
                sh 'bash ./Jenkins/Scripts/Docker/install-docker.sh'
                sh 'bash ./Jenkins/Scripts/Docker/build_images.sh'
            }
        }
        }
    }
}
